#include "cadnext/fea/StructuralReport.hpp"

#include <string>

#include "ModalReportTemplate.inc"      // generated by CMake from fea/report/modal-report.html
#include "StructuralReportTemplate.inc" // generated by CMake from fea/report/structural-report.html

namespace cadnext::fea {

namespace {

// JSON inside <script type="application/json">: only "</" can end the element early.
std::string scriptSafe(const std::string& json) {
    std::string out;
    out.reserve(json.size());
    for (std::size_t i = 0; i < json.size(); ++i) {
        if (json[i] == '<' && i + 1 < json.size() && json[i + 1] == '/') {
            out += "<\\/";
            ++i;
        } else {
            out += json[i];
        }
    }
    return out;
}

void replaceOnce(std::string& text, const std::string& token, const std::string& value) {
    const auto at = text.find(token);
    if (at != std::string::npos) text.replace(at, token.size(), value);
}

std::string filled(std::string html, const std::string& resultJson, const std::string& fieldJson) {
    replaceOnce(html, "__CADNEXT_RESULT_JSON__", scriptSafe(resultJson));
    replaceOnce(html, "__CADNEXT_FIELD_JSON__", scriptSafe(fieldJson));
    return html;
}

} // namespace

std::string structuralReportHtml(const std::string& resultJson, const std::string& fieldJson) {
    return filled(kStructuralReportTemplate, resultJson, fieldJson);
}

std::string modalReportHtml(const std::string& resultJson, const std::string& fieldJson) {
    return filled(kModalReportTemplate, resultJson, fieldJson);
}

} // namespace cadnext::fea
