#pragma once

#include <cstddef>
#include <span>

// The tables NativeSolidWorksAssemblyBlueprint.cpp holds (generated by
// ~/cadnext-samples/tools/solidworks_blueprint/gen_asm_cpp.py from three assemblies SOLIDWORKS 2022 made
// from STEP files); read by NativeSolidWorksAssembly.cpp.
namespace cadnext::gui::solidworks_assembly_blueprint {

// A piece of a stream:
//   'B' native bytes (text: hex)                      'S' an MFC string, as is
//   'V' an MFC string slot (text: its template — {title}, {name}, {folder}, {author}, {configuration})
//   'I' an integer of `number` bytes, a + b·n + c·k (text: "a,b,c"; n the components, k the block's index)
//   'T' a Unix time, 32 bits                          'F' / 'G' a FILETIME, low or high half first
//   'O' the box of the block's component part (10 doubles: centre, max, min, half diagonal; metres)
//   'A' the assembly's sphere and box (10 doubles: sphere centre, box max, box min, sphere radius)
//   'U' the document's GUID (16 bytes)                'Z' `number` bytes of unknown meaning (text: default hex)
struct Piece {
    char kind;
    unsigned short number;
    const char* text;
};

struct Section {
    const Piece* pieces;
    std::size_t count;
};

// Constant: the prefix's bytes. Whole: one section (prefix). Components: prefix, first component,
// then each further component's body, a separator after all but the last, then the tail; the
// components in tree order, or reversed.
enum class Layout { Constant, Whole, Components };

struct Stream {
    const char* name;
    Layout layout;
    bool reverse;
    Section prefix, first, body, sep, tail;
};

struct Entry {
    const char* name;
    unsigned stamp;
};

std::span<const Stream> streams();
std::span<const Entry> entries();     // the package's streams in order, with their stamps

} // namespace cadnext::gui::solidworks_assembly_blueprint
