import Foundation

/// Streams raw returns straight to disk as they are produced, so the complete record of a survey is
/// bounded by free space rather than by RAM.
///
/// The in-memory raw cloud remains, but only as a **preview** for the live view and for a quick
/// export; it keeps a cap because it is an array in a running simulator. The file has no cap: a long
/// sortie writes tens of millions of returns and none of them are lost.
///
/// A streamed PLY has one structural problem — `element vertex N` sits in the header, but `N` is not
/// known until the last return has been written. Rather than buffer the whole body or copy the file
/// at the end, the count is reserved as a fixed-width, zero-padded decimal field and patched in
/// place on close. The header keeps exactly the same byte length either way, so nothing after it
/// shifts, and leading zeros are valid decimal for every PLY reader.
final class LidarRawStreamWriter {

    /// Digits reserved for the vertex count — 12 covers a trillion returns.
    private static let countFieldWidth = 12
    /// Flush threshold. One tick produces a few kilobytes; batching keeps this to roughly one write
    /// per second instead of one per frame.
    private static let flushThresholdBytes = 256 * 1024

    let url: URL
    private(set) var writtenCount: Int = 0

    private let handle: FileHandle
    private let countFieldOffset: UInt64
    private let colorMode: LidarColorMode
    private let elevationMinimum: Float
    private let elevationMaximum: Float
    private var buffer = Data()
    private var isClosed = false

    /// - Parameter elevationReference: fixed vertical span for the height ramp. A stream cannot use
    ///   the cloud's own min/max — they are unknown while it is being written, and would make early
    ///   points a different colour from late ones. The world's extent is stable and stated in the
    ///   header, so the ramp means the same thing for every point in the file.
    init?(
        url: URL,
        colorMode: LidarColorMode,
        elevationReference: (minimum: Float, maximum: Float),
        comment: String,
        trajectoryFileName: String,
        epochUTC: String
    ) {
        self.url = url
        self.colorMode = colorMode
        self.elevationMinimum = elevationReference.minimum
        self.elevationMaximum = elevationReference.maximum

        var header = ""
        header += "ply\n"
        header += "format binary_little_endian 1.0\n"
        header += "comment Generated by UAVsim LiDAR payload — RAW RETURNS (streamed)\n"
        header += "comment \(comment)\n"
        header += "comment colour_mode \(colorMode.rawValue)\n"
        header += "comment height ramp reference span "
        header += "\(elevationReference.minimum) .. \(elevationReference.maximum) m\n"
        header += "comment timestamps are seconds from the survey epoch \(epochUTC)\n"
        header += "comment sensor trajectory: \(trajectoryFileName) (one row per scan_id, "
        header += "including scans with zero returns)\n"
        header += "comment scan_id is one firing block; channels share its instant, ring adds a "
        header += "fixed inter-channel offset\n"
        header += "comment classification codes follow ASPRS LAS\n"
        header += "element vertex "

        let prefix = Data(header.utf8)
        let countField = Data(String(repeating: "0", count: Self.countFieldWidth).utf8)
        var tail = "\n"
        tail += LidarRawCloud.propertyHeaderText
        tail += "end_header\n"

        let fileManager = FileManager.default
        guard fileManager.createFile(
            atPath: url.path,
            contents: prefix + countField + Data(tail.utf8)
        ), let handle = try? FileHandle(forWritingTo: url) else {
            return nil
        }
        self.handle = handle
        self.countFieldOffset = UInt64(prefix.count)
        try? handle.seekToEnd()
        buffer.reserveCapacity(Self.flushThresholdBytes + 4_096)
    }

    /// Appends a whole firing block. Blocks are written entire — a scan is never half-recorded.
    func write(_ returns: [LidarRawCloud.Return]) {
        guard !isClosed, !returns.isEmpty else { return }
        for entry in returns {
            LidarRawCloud.appendRecord(
                &buffer,
                entry,
                colorMode: colorMode,
                elevationMinimum: elevationMinimum,
                elevationMaximum: elevationMaximum
            )
        }
        writtenCount += returns.count
        if buffer.count >= Self.flushThresholdBytes {
            flush()
        }
    }

    private func flush() {
        guard !buffer.isEmpty else { return }
        try? handle.write(contentsOf: buffer)
        buffer.removeAll(keepingCapacity: true)
    }

    /// Flushes, patches the vertex count into the reserved field and closes. Returns the file, or
    /// nil if nothing was ever written to it.
    @discardableResult
    func finish() -> URL? {
        guard !isClosed else { return writtenCount > 0 ? url : nil }
        isClosed = true
        flush()

        let digits = String(writtenCount)
        let padded = String(repeating: "0", count: max(0, Self.countFieldWidth - digits.count))
            + digits.suffix(Self.countFieldWidth)
        try? handle.seek(toOffset: countFieldOffset)
        try? handle.write(contentsOf: Data(padded.utf8))
        try? handle.close()
        return writtenCount > 0 ? url : nil
    }

    /// Closes and removes the file — used when the survey is discarded rather than exported.
    func discard() {
        guard !isClosed else { return }
        isClosed = true
        buffer.removeAll(keepingCapacity: false)
        try? handle.close()
        try? FileManager.default.removeItem(at: url)
    }
}
