import Foundation
import simd

// MARK: - Raw returns

/// Every return the scanner produced, unfiltered — the sensor's own record.
///
/// Each entry describes one echo of one pulse, so every field is literally true of it: `range` is
/// the distance that pulse measured, `timestamp` the instant it fired, `scanID`/`ring` the firing
/// block and channel it came from, `returnNumber`/`numberOfReturns` its place in that pulse's echo
/// train. This is the only product in which sensor noise, multi-echo structure and motion
/// distortion survive, and the only one that can be de-skewed against the trajectory.
struct LidarRawCloud {

    struct Return {
        /// Local ENU metres: +X east, +Y up, +Z north.
        var position: SIMD3<Float>
        /// Return strength in [0, 1] — surface reflectance × incidence × range falloff.
        var intensity: Float
        /// Sensor-to-surface distance in metres, as measured (noise included).
        var range: Float
        /// Seconds since the survey epoch.
        var timestamp: Double
        /// Firing block this echo belongs to.
        var scanID: UInt32
        /// Channel within the block.
        var ring: UInt16
        var classification: LidarSurfaceClass
        /// 1-based index of this echo within its pulse.
        var returnNumber: UInt8
        /// Echoes that pulse produced in total.
        var numberOfReturns: UInt8
    }

    private(set) var returns: [Return] = []
    let maximumReturns: Int

    private(set) var minBounds = SIMD3<Float>(repeating: .greatestFiniteMagnitude)
    private(set) var maxBounds = SIMD3<Float>(repeating: -.greatestFiniteMagnitude)

    init(maximumReturns: Int = 1_500_000) {
        self.maximumReturns = max(1_000, maximumReturns)
    }

    var isEmpty: Bool { returns.isEmpty }
    var count: Int { returns.count }
    var isFull: Bool { returns.count >= maximumReturns }

    var elevationRange: (minimum: Float, maximum: Float)? {
        guard !returns.isEmpty else { return nil }
        return (minBounds.y, maxBounds.y)
    }

    @discardableResult
    mutating func append(_ entry: Return) -> Bool {
        guard returns.count < maximumReturns else { return false }
        returns.append(entry)
        minBounds = simd_min(minBounds, entry.position)
        maxBounds = simd_max(maxBounds, entry.position)
        return true
    }

    mutating func clear() {
        returns.removeAll(keepingCapacity: true)
        minBounds = SIMD3<Float>(repeating: .greatestFiniteMagnitude)
        maxBounds = SIMD3<Float>(repeating: -.greatestFiniteMagnitude)
    }

    /// `binary_little_endian` PLY of the raw returns — 40 bytes per vertex, fixed stride.
    func binaryPLYData(
        colorMode: LidarColorMode,
        comment: String,
        trajectoryFileName: String,
        epochUTC: String
    ) -> Data {
        let minimum = minBounds.y
        let maximum = maxBounds.y

        var header = ""
        header += "ply\n"
        header += "format binary_little_endian 1.0\n"
        header += "comment Generated by UAVsim LiDAR payload — RAW RETURNS\n"
        header += "comment \(comment)\n"
        header += "comment colour_mode \(colorMode.rawValue)\n"
        header += "comment timestamps are seconds from the survey epoch \(epochUTC)\n"
        header += "comment sensor trajectory: \(trajectoryFileName) (one row per scan_id, "
        header += "including scans with zero returns)\n"
        header += "comment scan_id is one firing block; channels share its instant, ring adds a "
        header += "fixed inter-channel offset\n"
        header += "comment classification codes follow ASPRS LAS\n"
        header += "element vertex \(returns.count)\n"
        header += "property float x\nproperty float y\nproperty float z\n"
        header += "property uchar red\nproperty uchar green\nproperty uchar blue\n"
        header += "property float intensity\n"
        header += "property float range\n"
        header += "property double timestamp\n"
        header += "property uint scan_id\n"
        header += "property ushort ring\n"
        header += "property uchar classification\n"
        header += "property uchar return_number\n"
        header += "property uchar number_of_returns\n"
        header += "end_header\n"

        // 12 + 3 + 4 + 4 + 8 + 4 + 2 + 1 + 1 + 1 = 40 bytes per vertex.
        var data = Data(header.utf8)
        data.reserveCapacity(header.utf8.count + returns.count * 40)
        for entry in returns {
            let color = LidarColorResolver.color(
                classification: entry.classification,
                intensity: entry.intensity,
                height: entry.position.y,
                mode: colorMode,
                elevationMinimum: minimum,
                elevationMaximum: maximum
            )
            LidarBinaryWriter.append(&data, entry.position.x)
            LidarBinaryWriter.append(&data, entry.position.y)
            LidarBinaryWriter.append(&data, entry.position.z)
            data.append(color.red)
            data.append(color.green)
            data.append(color.blue)
            LidarBinaryWriter.append(&data, entry.intensity)
            LidarBinaryWriter.append(&data, entry.range)
            LidarBinaryWriter.append(&data, entry.timestamp)
            LidarBinaryWriter.append(&data, entry.scanID)
            LidarBinaryWriter.append(&data, entry.ring)
            data.append(entry.classification.rawValue)
            data.append(entry.returnNumber)
            data.append(entry.numberOfReturns)
        }
        return data
    }

    func geoCSVData(origin: GeoOrigin) -> Data {
        var text = ""
        text.reserveCapacity(returns.count * 96 + 256)
        text += "latitude_deg,longitude_deg,altitude_msl_m,"
        text += "local_east_m,local_up_m,local_north_m,"
        text += "intensity,range_m,timestamp_s,scan_id,ring,classification,class_name,"
        text += "return_number,number_of_returns\n"
        for entry in returns {
            let coordinate = origin.geographic(ofLocalPosition: entry.position)
            text += String(
                format: "%.8f,%.8f,%.3f,%.3f,%.3f,%.3f,%.4f,%.3f,%.6f,%u,%u,%u,%@,%u,%u\n",
                coordinate.latitudeDegrees,
                coordinate.longitudeDegrees,
                coordinate.altitudeMetersMSL,
                Double(entry.position.x), Double(entry.position.y), Double(entry.position.z),
                Double(entry.intensity), Double(entry.range), entry.timestamp,
                entry.scanID, UInt32(entry.ring),
                UInt32(entry.classification.rawValue), entry.classification.label,
                UInt32(entry.returnNumber), UInt32(entry.numberOfReturns)
            )
        }
        return Data(text.utf8)
    }
}

// MARK: - Centroid map

/// The voxel-filtered map product: one point per occupied voxel, at the centroid of the returns
/// that fell in it.
///
/// Its schema is deliberately *not* the raw schema. A centroid aggregates echoes captured from
/// different poses, at different instants, on different channels — so it carries no `range`,
/// `scan_id` or `ring`, because inheriting those from one arbitrary contributing return would state
/// something false about the point. It carries honest aggregates instead: mean intensity, the
/// number of returns merged, the time span they cover, and the majority surface class. Anyone
/// needing per-echo truth reads the raw cloud.
struct LidarVoxelMap {

    struct Cell {
        /// Centroid of every return merged here.
        var position: SIMD3<Float>
        /// Mean return strength.
        var intensity: Float
        /// Majority class among the merged returns.
        var classification: LidarSurfaceClass
        /// How many returns this centroid averages — a direct measure of the noise reduction
        /// achieved here (zero-mean ranging noise falls as √n) and of survey overlap.
        var mergeCount: UInt32
        /// First and last instant contributing to this voxel — a span, not a single moment.
        var firstTimestamp: Double
        var lastTimestamp: Double
    }

    /// Running state behind a centroid, kept parallel to `cells`.
    private struct Accumulator {
        var positionSum: SIMD3<Double>
        var intensitySum: Double
        var count: UInt32
        /// Boyer–Moore majority vote: O(1) per return, exact when a true majority exists.
        var dominantClass: LidarSurfaceClass
        var dominantScore: Int32
    }

    enum InsertResult {
        case inserted(Int)
        case merged(Int)
        case rejected
    }

    private(set) var cells: [Cell] = []
    private var accumulators: [Accumulator] = []
    private var voxelIndex: [Int64: Int] = [:]
    private var occupiedColumns: Set<Int64> = []
    private(set) var totalReturns: UInt64 = 0

    private(set) var voxelSizeMeters: Float
    let maximumCells: Int

    private(set) var minBounds = SIMD3<Float>(repeating: .greatestFiniteMagnitude)
    private(set) var maxBounds = SIMD3<Float>(repeating: -.greatestFiniteMagnitude)

    init(voxelSizeMeters: Float = LidarVoxelSize.coarse.rawValue, maximumCells: Int = 1_200_000) {
        self.voxelSizeMeters = max(0.02, voxelSizeMeters)
        self.maximumCells = max(1_000, maximumCells)
    }

    var isEmpty: Bool { cells.isEmpty }
    var count: Int { cells.count }
    var isFull: Bool { cells.count >= maximumCells }

    var coverageSquareMeters: Float {
        let cell = max(voxelSizeMeters, 0.1)
        return Float(occupiedColumns.count) * cell * cell
    }

    var elevationRange: (minimum: Float, maximum: Float)? {
        guard !cells.isEmpty else { return nil }
        return (minBounds.y, maxBounds.y)
    }

    var meanReturnsPerCell: Float {
        guard !cells.isEmpty else { return 0 }
        return Float(Double(totalReturns) / Double(cells.count))
    }

    mutating func reconfigure(voxelSizeMeters: Float) {
        self.voxelSizeMeters = max(0.02, voxelSizeMeters)
        clear()
    }

    @discardableResult
    mutating func insert(
        position: SIMD3<Float>,
        intensity: Float,
        timestamp: Double,
        classification: LidarSurfaceClass
    ) -> InsertResult {
        guard cells.count < maximumCells else { return .rejected }
        guard position.x.isFinite, position.y.isFinite, position.z.isFinite else { return .rejected }

        let key = voxelKey(position)
        if let existing = voxelIndex[key] {
            accumulators[existing].positionSum += SIMD3<Double>(position)
            accumulators[existing].intensitySum += Double(intensity)
            accumulators[existing].count &+= 1
            if accumulators[existing].dominantClass == classification {
                accumulators[existing].dominantScore &+= 1
            } else {
                accumulators[existing].dominantScore &-= 1
                if accumulators[existing].dominantScore < 0 {
                    accumulators[existing].dominantClass = classification
                    accumulators[existing].dominantScore = 1
                }
            }
            totalReturns &+= 1

            let accumulator = accumulators[existing]
            let inverse = 1.0 / Double(accumulator.count)
            cells[existing].position = SIMD3<Float>(accumulator.positionSum * inverse)
            cells[existing].intensity = Float(accumulator.intensitySum * inverse)
            cells[existing].classification = accumulator.dominantClass
            cells[existing].mergeCount = accumulator.count
            cells[existing].firstTimestamp = min(cells[existing].firstTimestamp, timestamp)
            cells[existing].lastTimestamp = max(cells[existing].lastTimestamp, timestamp)
            expandBounds(cells[existing].position)
            return .merged(existing)
        }

        cells.append(Cell(
            position: position,
            intensity: intensity,
            classification: classification,
            mergeCount: 1,
            firstTimestamp: timestamp,
            lastTimestamp: timestamp
        ))
        accumulators.append(Accumulator(
            positionSum: SIMD3<Double>(position),
            intensitySum: Double(intensity),
            count: 1,
            dominantClass: classification,
            dominantScore: 1
        ))
        voxelIndex[key] = cells.count - 1
        occupiedColumns.insert(columnKey(position))
        totalReturns &+= 1
        expandBounds(position)
        return .inserted(cells.count - 1)
    }

    mutating func clear() {
        cells.removeAll(keepingCapacity: true)
        accumulators.removeAll(keepingCapacity: true)
        voxelIndex.removeAll(keepingCapacity: true)
        occupiedColumns.removeAll(keepingCapacity: true)
        totalReturns = 0
        minBounds = SIMD3<Float>(repeating: .greatestFiniteMagnitude)
        maxBounds = SIMD3<Float>(repeating: -.greatestFiniteMagnitude)
    }

    private mutating func expandBounds(_ position: SIMD3<Float>) {
        minBounds = simd_min(minBounds, position)
        maxBounds = simd_max(maxBounds, position)
    }

    private func quantise(_ value: Float) -> Int32 {
        Int32((value / voxelSizeMeters).rounded(.down))
    }

    private func voxelKey(_ position: SIMD3<Float>) -> Int64 {
        let x = Int64(quantise(position.x)) & 0x1F_FFFF
        let y = Int64(quantise(position.y)) & 0x1F_FFFF
        let z = Int64(quantise(position.z)) & 0x1F_FFFF
        return (x << 42) | (y << 21) | z
    }

    private func columnKey(_ position: SIMD3<Float>) -> Int64 {
        let x = Int64(quantise(position.x)) & 0xFFFF_FFFF
        let z = Int64(quantise(position.z)) & 0xFFFF_FFFF
        return (x << 32) | z
    }

    /// `binary_little_endian` PLY of the map product. `merge_count` is a **`uint`**: a survey that
    /// dwells over one façade merges far more than 255 returns into a voxel, and a saturating byte
    /// would silently understate exactly the overlap statistic this field exists to report.
    func binaryPLYData(
        colorMode: LidarColorMode,
        comment: String,
        rawFileName: String?,
        epochUTC: String
    ) -> Data {
        let minimum = minBounds.y
        let maximum = maxBounds.y

        var header = ""
        header += "ply\n"
        header += "format binary_little_endian 1.0\n"
        header += "comment Generated by UAVsim LiDAR payload — VOXEL CENTROID MAP\n"
        header += "comment \(comment)\n"
        header += "comment colour_mode \(colorMode.rawValue)\n"
        header += "comment timestamps are seconds from the survey epoch \(epochUTC)\n"
        header += "comment a centroid aggregates returns from several poses, instants and channels,"
        header += " so it carries no range/scan_id/ring — see the raw cloud for per-echo values\n"
        if let rawFileName {
            header += "comment raw returns: \(rawFileName)\n"
        }
        header += "comment classification is the majority class of the merged returns\n"
        header += "comment classification codes follow ASPRS LAS\n"
        header += "element vertex \(cells.count)\n"
        header += "property float x\nproperty float y\nproperty float z\n"
        header += "property uchar red\nproperty uchar green\nproperty uchar blue\n"
        header += "property float intensity\n"
        header += "property uchar classification\n"
        header += "property uint merge_count\n"
        header += "property double first_timestamp\n"
        header += "property double last_timestamp\n"
        header += "end_header\n"

        // 12 + 3 + 4 + 1 + 4 + 8 + 8 = 40 bytes per vertex.
        var data = Data(header.utf8)
        data.reserveCapacity(header.utf8.count + cells.count * 40)
        for cell in cells {
            let color = LidarColorResolver.color(
                classification: cell.classification,
                intensity: cell.intensity,
                height: cell.position.y,
                mode: colorMode,
                elevationMinimum: minimum,
                elevationMaximum: maximum
            )
            LidarBinaryWriter.append(&data, cell.position.x)
            LidarBinaryWriter.append(&data, cell.position.y)
            LidarBinaryWriter.append(&data, cell.position.z)
            data.append(color.red)
            data.append(color.green)
            data.append(color.blue)
            LidarBinaryWriter.append(&data, cell.intensity)
            data.append(cell.classification.rawValue)
            LidarBinaryWriter.append(&data, cell.mergeCount)
            LidarBinaryWriter.append(&data, cell.firstTimestamp)
            LidarBinaryWriter.append(&data, cell.lastTimestamp)
        }
        return data
    }

    func geoCSVData(origin: GeoOrigin) -> Data {
        var text = ""
        text.reserveCapacity(cells.count * 88 + 256)
        text += "latitude_deg,longitude_deg,altitude_msl_m,"
        text += "local_east_m,local_up_m,local_north_m,"
        text += "mean_intensity,classification,class_name,merge_count,"
        text += "first_timestamp_s,last_timestamp_s\n"
        for cell in cells {
            let coordinate = origin.geographic(ofLocalPosition: cell.position)
            text += String(
                format: "%.8f,%.8f,%.3f,%.3f,%.3f,%.3f,%.4f,%u,%@,%u,%.6f,%.6f\n",
                coordinate.latitudeDegrees,
                coordinate.longitudeDegrees,
                coordinate.altitudeMetersMSL,
                Double(cell.position.x), Double(cell.position.y), Double(cell.position.z),
                Double(cell.intensity),
                UInt32(cell.classification.rawValue), cell.classification.label,
                cell.mergeCount,
                cell.firstTimestamp, cell.lastTimestamp
            )
        }
        return Data(text.utf8)
    }
}

// MARK: - Trajectory

/// Pose of one firing block. A multi-channel head fires its whole vertical fan at one instant, so a
/// block has a single pose — motion between blocks is what deskewing corrects, and this table is
/// what makes that possible without back-computing the sensor from the points.
///
/// `returnsInScan` is recorded for **every** block, including those that produced nothing: that is
/// what separates a genuinely empty block from one dropped under load or lost in export.
struct LidarScanPose {
    let scanID: UInt32
    let timestamp: Double
    let sensorPosition: SIMD3<Float>
    let sensorOrientation: simd_quatf
    let vehiclePosition: SIMD3<Float>
    let vehicleOrientation: simd_quatf
    let returnsInScan: Int
}

enum LidarTrajectoryWriter {
    static func csvData(poses: [LidarScanPose], origin: GeoOrigin?) -> Data {
        var text = ""
        text += "scan_id,timestamp_s,"
        text += "sensor_east_m,sensor_up_m,sensor_north_m,"
        text += "sensor_qx,sensor_qy,sensor_qz,sensor_qw,"
        text += "uav_east_m,uav_up_m,uav_north_m,uav_qx,uav_qy,uav_qz,uav_qw,"
        text += "returns_in_scan,sensor_latitude_deg,sensor_longitude_deg,sensor_altitude_msl_m\n"
        for pose in poses {
            var line = String(
                format: "%u,%.6f,%.3f,%.3f,%.3f,",
                pose.scanID, pose.timestamp,
                Double(pose.sensorPosition.x), Double(pose.sensorPosition.y),
                Double(pose.sensorPosition.z)
            )
            line += String(
                format: "%.6f,%.6f,%.6f,%.6f,",
                Double(pose.sensorOrientation.imag.x), Double(pose.sensorOrientation.imag.y),
                Double(pose.sensorOrientation.imag.z), Double(pose.sensorOrientation.real)
            )
            line += String(
                format: "%.3f,%.3f,%.3f,%.6f,%.6f,%.6f,%.6f,%d",
                Double(pose.vehiclePosition.x), Double(pose.vehiclePosition.y),
                Double(pose.vehiclePosition.z),
                Double(pose.vehicleOrientation.imag.x), Double(pose.vehicleOrientation.imag.y),
                Double(pose.vehicleOrientation.imag.z), Double(pose.vehicleOrientation.real),
                pose.returnsInScan
            )
            if let origin {
                let coordinate = origin.geographic(ofLocalPosition: pose.sensorPosition)
                line += String(
                    format: ",%.8f,%.8f,%.3f",
                    coordinate.latitudeDegrees, coordinate.longitudeDegrees,
                    coordinate.altitudeMetersMSL
                )
            } else {
                line += ",,,"
            }
            text += line + "\n"
        }
        return Data(text.utf8)
    }
}

// MARK: - Shared helpers

enum LidarColorResolver {
    static func color(
        classification: LidarSurfaceClass,
        intensity: Float,
        height: Float,
        mode: LidarColorMode,
        elevationMinimum: Float,
        elevationMaximum: Float
    ) -> (red: UInt8, green: UInt8, blue: UInt8) {
        switch mode {
        case .height:
            return elevationColor(y: height, minimum: elevationMinimum, maximum: elevationMaximum)
        case .intensity:
            let value = UInt8(max(0, min(255, intensity * 255)))
            return (value, value, value)
        case .material:
            return classification.materialColor
        case .semantic:
            return classification.semanticColor
        }
    }

    /// Blue (low) → green → yellow → red (high) over the cloud's own vertical span.
    static func elevationColor(
        y: Float,
        minimum: Float,
        maximum: Float
    ) -> (red: UInt8, green: UInt8, blue: UInt8) {
        let span = max(0.001, maximum - minimum)
        let t = max(0, min(1, (y - minimum) / span))
        let stops: [(Float, Float, Float)] = [
            (0.13, 0.32, 0.75),
            (0.20, 0.70, 0.45),
            (0.85, 0.80, 0.25),
            (0.85, 0.22, 0.18)
        ]
        let scaled = t * Float(stops.count - 1)
        let index = min(stops.count - 2, Int(scaled))
        let localT = scaled - Float(index)
        let a = stops[index]
        let b = stops[index + 1]
        func channel(_ lhs: Float, _ rhs: Float) -> UInt8 {
            UInt8(max(0, min(255, (lhs + (rhs - lhs) * localT) * 255)))
        }
        return (channel(a.0, b.0), channel(a.1, b.1), channel(a.2, b.2))
    }
}

enum LidarBinaryWriter {
    static func append(_ data: inout Data, _ value: Float) {
        withUnsafeBytes(of: value.bitPattern.littleEndian) { data.append(contentsOf: $0) }
    }

    static func append(_ data: inout Data, _ value: Double) {
        withUnsafeBytes(of: value.bitPattern.littleEndian) { data.append(contentsOf: $0) }
    }

    static func append(_ data: inout Data, _ value: UInt32) {
        withUnsafeBytes(of: value.littleEndian) { data.append(contentsOf: $0) }
    }

    static func append(_ data: inout Data, _ value: UInt16) {
        withUnsafeBytes(of: value.littleEndian) { data.append(contentsOf: $0) }
    }
}

/// Live survey read-out handed back to the HUD.
struct LidarScanStatistics {
    let mapPointCount: Int
    let rawReturnCount: Int
    let coverageSquareMeters: Double
    let meanReturnsPerPoint: Double
    let scanCount: Int
    let isBufferFull: Bool
}
