# CMake generated Testfile for 
# Source directory: /Users/misha/UAVsim/CADNext/tests
# Build directory: /Users/misha/UAVsim/CADNext/build/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[cadnext_test_sketch_model]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_sketch_model")
set_tests_properties([=[cadnext_test_sketch_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;388;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_units_mm_format]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_units_mm_format")
set_tests_properties([=[cadnext_test_units_mm_format]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;389;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_sketch_dimension_measurements]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_sketch_dimension_measurements")
set_tests_properties([=[cadnext_test_sketch_dimension_measurements]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;390;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_sketch_snap]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_sketch_snap")
set_tests_properties([=[cadnext_test_sketch_snap]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;392;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_sketch_plane_mapping]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_sketch_plane_mapping")
set_tests_properties([=[cadnext_test_sketch_plane_mapping]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;393;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_sketch_reference_projection]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_sketch_reference_projection")
set_tests_properties([=[cadnext_test_sketch_reference_projection]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;394;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_workplane_visibility_policy]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_workplane_visibility_policy")
set_tests_properties([=[cadnext_test_workplane_visibility_policy]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;396;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_sketch2d_view_state]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_sketch2d_view_state")
set_tests_properties([=[cadnext_test_sketch2d_view_state]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;398;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_camera_navigation_state]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_camera_navigation_state")
set_tests_properties([=[cadnext_test_camera_navigation_state]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;399;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_escape_navigation_policy]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_escape_navigation_policy")
set_tests_properties([=[cadnext_test_escape_navigation_policy]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;401;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_view_bounds_policy]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_view_bounds_policy")
set_tests_properties([=[cadnext_test_view_bounds_policy]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;403;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_camera_focus_target]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_camera_focus_target")
set_tests_properties([=[cadnext_test_camera_focus_target]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;404;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_sketch_reference_mapping]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_sketch_reference_mapping")
set_tests_properties([=[cadnext_test_sketch_reference_mapping]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;405;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_extrude_parameters]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_extrude_parameters")
set_tests_properties([=[cadnext_test_extrude_parameters]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;407;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_extrude_direction]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_extrude_direction")
set_tests_properties([=[cadnext_test_extrude_direction]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;408;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_extrude_serialization]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_extrude_serialization")
set_tests_properties([=[cadnext_test_extrude_serialization]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;409;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_extrude_cut_parameters]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_extrude_cut_parameters")
set_tests_properties([=[cadnext_test_extrude_cut_parameters]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;411;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_extrude_cut_depth_modes]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_extrude_cut_depth_modes")
set_tests_properties([=[cadnext_test_extrude_cut_depth_modes]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;413;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_chamfer_parameters]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_chamfer_parameters")
set_tests_properties([=[cadnext_test_chamfer_parameters]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;415;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_fillet_parameters]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_fillet_parameters")
set_tests_properties([=[cadnext_test_fillet_parameters]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;417;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_face_reference]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_face_reference")
set_tests_properties([=[cadnext_test_face_reference]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;419;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_edge_reference]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_edge_reference")
set_tests_properties([=[cadnext_test_edge_reference]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;420;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_edge_reference_refresh]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_edge_reference_refresh")
set_tests_properties([=[cadnext_test_edge_reference_refresh]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;421;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_face_mesh_ownership]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_face_mesh_ownership")
set_tests_properties([=[cadnext_test_face_mesh_ownership]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;423;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_procedural_prism_face_ids]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_procedural_prism_face_ids")
set_tests_properties([=[cadnext_test_procedural_prism_face_ids]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;425;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_face_sketch_reference]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_face_sketch_reference")
set_tests_properties([=[cadnext_test_face_sketch_reference]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;427;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_face_selection_resolution]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_face_selection_resolution")
set_tests_properties([=[cadnext_test_face_selection_resolution]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;429;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_body_face_selection_state]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_body_face_selection_state")
set_tests_properties([=[cadnext_test_body_face_selection_state]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;431;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_face_workplane_serialization]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_face_workplane_serialization")
set_tests_properties([=[cadnext_test_face_workplane_serialization]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;433;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_workplane_model]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_workplane_model")
set_tests_properties([=[cadnext_test_workplane_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;435;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_sketch_reference]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_sketch_reference")
set_tests_properties([=[cadnext_test_sketch_reference]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;436;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_sketch_serialization]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_sketch_serialization")
set_tests_properties([=[cadnext_test_sketch_serialization]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;437;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_sketch_profile_detector]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_sketch_profile_detector")
set_tests_properties([=[cadnext_test_sketch_profile_detector]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;438;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_custom_profile_stability]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_custom_profile_stability")
set_tests_properties([=[cadnext_test_custom_profile_stability]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;439;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_document]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_document")
set_tests_properties([=[cadnext_test_document]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;441;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_stub_kernel]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_stub_kernel")
set_tests_properties([=[cadnext_test_stub_kernel]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;442;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_bridge_export]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_bridge_export")
set_tests_properties([=[cadnext_test_bridge_export]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;443;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_uavpart_format]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_uavpart_format")
set_tests_properties([=[cadnext_test_uavpart_format]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;444;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_primitive_object]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_primitive_object")
set_tests_properties([=[cadnext_test_primitive_object]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;445;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_document_editing]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_document_editing")
set_tests_properties([=[cadnext_test_document_editing]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;446;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_document_serialization]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_document_serialization")
set_tests_properties([=[cadnext_test_document_serialization]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;447;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_command_stack]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_command_stack")
set_tests_properties([=[cadnext_test_command_stack]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;448;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_geometry_evaluator_fallback]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_geometry_evaluator_fallback")
set_tests_properties([=[cadnext_test_geometry_evaluator_fallback]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;449;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_kernel_primitives]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_kernel_primitives")
set_tests_properties([=[cadnext_test_occt_kernel_primitives]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;597;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_mesh_extractor]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_mesh_extractor")
set_tests_properties([=[cadnext_test_occt_mesh_extractor]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;599;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_geometry_evaluator]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_geometry_evaluator")
set_tests_properties([=[cadnext_test_geometry_evaluator]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;601;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_extrude_cut]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_extrude_cut")
set_tests_properties([=[cadnext_test_occt_extrude_cut]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;603;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_planar_face_analyzer]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_planar_face_analyzer")
set_tests_properties([=[cadnext_test_occt_planar_face_analyzer]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;605;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_mesh_face_ids]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_mesh_face_ids")
set_tests_properties([=[cadnext_test_occt_mesh_face_ids]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;607;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_face_pick_resolution]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_face_pick_resolution")
set_tests_properties([=[cadnext_test_occt_face_pick_resolution]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;609;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_edge_analyzer]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_edge_analyzer")
set_tests_properties([=[cadnext_test_occt_edge_analyzer]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;611;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_chamfer]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_chamfer")
set_tests_properties([=[cadnext_test_occt_chamfer]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;613;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_fillet]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_fillet")
set_tests_properties([=[cadnext_test_occt_fillet]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;615;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_sketch_on_face_extrude_cut]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_sketch_on_face_extrude_cut")
set_tests_properties([=[cadnext_test_occt_sketch_on_face_extrude_cut]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;617;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_chamfer_distance_angle]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_chamfer_distance_angle")
set_tests_properties([=[cadnext_test_occt_chamfer_distance_angle]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;619;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_chamfer_after_cut]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_chamfer_after_cut")
set_tests_properties([=[cadnext_test_occt_chamfer_after_cut]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;621;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_fillet_after_cut]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_fillet_after_cut")
set_tests_properties([=[cadnext_test_occt_fillet_after_cut]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;623;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_edge_reanalysis_after_topology_change]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_edge_reanalysis_after_topology_change")
set_tests_properties([=[cadnext_test_occt_edge_reanalysis_after_topology_change]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;625;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
add_test([=[cadnext_test_occt_mass_properties]=] "/Users/misha/UAVsim/CADNext/build/tests/cadnext_test_occt_mass_properties")
set_tests_properties([=[cadnext_test_occt_mass_properties]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;627;add_test;/Users/misha/UAVsim/CADNext/tests/CMakeLists.txt;0;")
