"""Thirty additional exterior assets researched on 2026-10-06.

Dimensions are in metres. Only values explicitly listed in ``published`` are
claimed as published measurements; other shaping dimensions are visual estimates.
These entries deliberately do not invent flight-dynamics profiles for the app.
"""

DATE = '2026-10-06'


def aircraft(ident, name, layout, span, length, source, published, **shape):
    return dict(id=ident, name=name, category='vtol' if shape.get('vtol') else 'fixed-wing',
                layout=layout, wingspan_m=span, length_m=length, source_url=source,
                published=published, shape=shape)


CATALOG = [
    aircraft('wingtra-ray', 'WingtraRAY', 'ray', 1.25, .68,
             'https://wingtra.com/ray/', '125 × 68 × 12 cm, without landing fin',
             vtol=True, height=.12, paint='ray_orange'),
    aircraft('ageagle-ebee-x', 'AgEagle eBee X', 'ebee', 1.16, .58,
             'https://eaglenxt.com/products/drones/ebee-series/ebee-x/',
             'Wingspan 116 cm; length is estimated from imagery', paint='epp_black'),
    aircraft('delair-dt26-open-payload', 'Delair DT26 Open Payload', 'dt26', 3.3, 1.6,
             'https://delair.aero/delair-commercial-drones-2/dt26-open-payload/',
             'Wingspan / length: 3.3 m / 1.6 m', paint='paint_white'),
    aircraft('jouav-cw-20e', 'JOUAV CW-20E', 'cw20', 3.50, 2.07,
             'https://www.jouav.com/products/cw-20e.html',
             'Technical Specifications: wingspan 3.50 m; fuselage 2.07 m',
             vtol=True, paint='paint_white'),
    aircraft('delair-ux11', 'Delair UX11', 'ux11', 1.2, .75,
             'https://delair.aero/drone-solutions-for-geospatial-surveying-and-mapping/',
             'Wingspan 1.2 m; length is estimated from imagery', paint='paint_white'),
    aircraft('c-astral-bramor-c4eye', 'C-Astral Bramor C4EYE', 'bramor', 2.3, .96,
             'https://www.c-astral.com/en/unmanned-systems/bramor-c4eye',
             'Wingspan 230 cm; platform length 96 cm; centre module length 67 cm',
             paint='paint_gray'),
    aircraft('aerovironment-puma-le', 'AeroVironment Puma LE', 'puma', 4.6, 2.2,
             'https://www.avinc.com/solution/puma-le/', 'Wingspan 4.6 m; length 2.2 m',
             paint='paint_sand', long_endurance=True),
    aircraft('tekever-ar3', 'TEKEVER AR3', 'ar3', 3.5, 1.7,
             'https://www.tekever.com/wp-content/uploads/2023/06/Products_v02_2023.pdf',
             'AR3: wingspan 3.5 m; length 1.7 m; fixed-wing configuration', paint='paint_white'),
    aircraft('deltaquad-evo', 'DeltaQuad Evo', 'deltaquad', 2.69, .75,
             'https://www.deltaquad.com/resources/technical-specifications/',
             'Wingspan 269 cm; length 75 cm; height 33 cm with landing gear',
             vtol=True, paint='paint_white', height=.33),
    aircraft('tekever-ar5', 'TEKEVER AR5', 'ar5', 7.3, 4.0,
             'https://www.tekever.com/wp-content/uploads/2023/06/Products_v02_2023.pdf',
             'AR5: wingspan 7.3 m; length 4.0 m', paint='paint_white'),
    aircraft('aerovironment-raven-b', 'AeroVironment Raven B', 'raven', 1.4, .9,
             'https://www.avinc.com/solution/raven-b/', 'Wingspan 1.4 m; length 0.9 m',
             paint='paint_sand'),
    aircraft('aerovironment-puma-3-ae', 'AeroVironment Puma 3 AE', 'puma', 2.8, 1.4,
             'https://www.avinc.com/solution/puma-3-ae/', 'Wingspan 2.8 m; length 1.4 m',
             paint='paint_sand'),
    aircraft('aerovironment-jump-20', 'AeroVironment JUMP 20', 'jump', 5.7, 2.8,
             'https://www.avinc.com/solution/jump-20/', 'Wingspan 5.7 m; length 2.8 m',
             vtol=True, paint='paint_gray'),
    aircraft('insitu-scaneagle', 'Insitu ScanEagle', 'scaneagle', 3.1, 1.71,
             'https://www.insitu.com/products/scaneagle', 'Wingspan 3.1 m; length 1.71 m',
             paint='paint_white'),
    aircraft('aeronautics-orbiter-3', 'Aeronautics Orbiter 3', 'orbiter', 4.2, 1.2,
             'https://aeronautics-sys.com/systems/orbiter-3/',
             'Wingspan 4.2 m; length is estimated from reference imagery',
             paint='paint_gray', revision=3),
    aircraft('aeronautics-orbiter-4', 'Aeronautics Orbiter 4', 'orbiter', 5.4, 1.5,
             'https://www.aeronautics-sys.com/wp-content/uploads/2023/01/Orbiter4.pdf',
             'Wingspan 5.4 m; length is estimated from reference imagery',
             paint='paint_gray', revision=4),
    aircraft('aeronautics-aerostar', 'Aeronautics Aerostar', 'twinboom', 8.7, 4.5,
             'https://aeronautics-sys.com/systems/aerostar/',
             'Wingspan 8.7 m; fuselage length 4.5 m', paint='paint_white', tail='inverted-v', gear=True),
    aircraft('elbit-hermes-450', 'Elbit Hermes 450', 'male', 10.5, 6.1,
             'https://www.mindef.gov.sg/news-and-events/latest-releases/2015mar30-news-releases-01655/',
             'Wingspan 10.5 m; length 6.1 m', paint='paint_gray', tail='v', gear=True),
    aircraft('iai-heron-mk-ii', 'IAI Heron Mk II', 'twinboom', 16.6, 8.5,
             'https://www.iai.co.il/product/heron-mk-ii/',
             'Wingspan 16.6 m; fuselage length 8.5 m', paint='paint_gray', tail='h', gear=True, dome=True),
    aircraft('iai-heron-tp', 'IAI Heron TP', 'twinboom', 26., 14.,
             'https://www.iai.co.il/product/heron-tp/',
             'Wingspan 26 m; length 14 m', paint='paint_gray', tail='h', gear=True, dome=True, turboprop=True),
    aircraft('baykar-bayraktar-tb2', 'Baykar Bayraktar TB2', 'tb', 12., 6.5,
             'https://baykartech.com/en/uav/bayraktar-tb2/',
             'Wingspan 12 m; length 6.5 m', paint='paint_gray', gear=True, revision=2),
    aircraft('baykar-bayraktar-tb3', 'Baykar Bayraktar TB3', 'tb', 14., 8.35,
             'https://baykartech.com/en/press/naval-variant-of-the-famous-bayraktar-drone-ready-for-first-flight/',
             'Wingspan 14 m; length 8.35 m', paint='paint_gray', gear=True, revision=3),
    aircraft('baykar-akinci', 'Baykar AKINCI', 'akinci', 20., 12.3,
             'https://cdn.baykartech.com/media/upload/userFormUpload/A9hsTup1Jbq6SqmJ5M6Zec0WyWXofrWX.pdf',
             'Wingspan 20 m; length 12.3 m', paint='paint_gray', gear=True),
    aircraft('baykar-kizilelma', 'Baykar KIZILELMA', 'kizilelma', 10., 14.5,
             'https://baykartech.com/en/uav/bayraktar-kizilelma/',
             'Wingspan 10 m; length 14.5 m', paint='paint_gray', gear=True),
    aircraft('leonardo-falco-evo', 'Leonardo Falco EVO', 'twinboom', 12.5, 5.2,
             'https://aeronautics.leonardo.com/documents/30508878/30801272/FALCO_EVO_MM07818-VEL.pdf?t=1675434951098',
             'Wingspan 12.5 m; length 5.2 m', paint='paint_gray', tail='inverted-v', gear=True),
    aircraft('leonardo-falco-xplorer', 'Leonardo Falco Xplorer', 'male', 18.5, 9.,
             'https://aeronautics.leonardo.com/en/products/falco-xplorer',
             'Wingspan 18.5 m; length 9 m', paint='paint_white', tail='v', gear=True, dome=True),
    aircraft('piaggio-p1hh-hammerhead', 'Piaggio P.1HH HammerHead', 'piaggio', 15.6, 14.4,
             'https://www.piaggioaerospace.it/yep-content/media/P1HH_HammerHead_B.pdf',
             'Wingspan 15.6 m; length 14.4 m', paint='paint_white', gear=True),
    dict(id='dji-mini-5-pro', name='DJI Mini 5 Pro', category='multicopter', layout='mini5',
         source_url='https://www.dji.com/mini-5-pro/specs',
         published='Unfolded, with propellers: 304 × 380 × 91 mm (L × W × H)',
         dimensions_m=[.380, .091, .304], shape={}),
    dict(id='dji-avata-2', name='DJI Avata 2', category='multicopter', layout='avata2',
         source_url='https://www.dji.com/avata-2/specs',
         published='185 × 212 × 64 mm (L × W × H)',
         dimensions_m=[.212, .064, .185], shape={}),
    dict(id='autel-evo-max-4t-v2', name='Autel EVO Max 4T V2', category='multicopter', layout='autel',
         source_url='https://www.autelrobotics.com/wp-content/uploads/2025/05/EVO-Max-Series-Brochure.pdf',
         published='Unfolded with 1158 propellers: 563 × 657 × 147 mm (L × W × H); wheelbase 467 mm',
         dimensions_m=[.657, .147, .563], shape={}),
]

assert len(CATALOG) == 30
assert len({p['id'] for p in CATALOG}) == 30
